{
 "title": "Air Quality (influxQL)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "AQI d3928b",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/d3928b/AQI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AQI cf52c4",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/cf52c4/AQI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AQI Meaning",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "options": {
    "content": "\n<div>\n<span style=\"background-color: #009966; margin:5px;\">&nbsp;&nbsp;</span>\n Good\n</div>\n\n<div >\n<span style=\"background-color: #ffde33;  margin:5px;\">&nbsp;&nbsp;</span>\n Moderate\n</div>\n\n<div >\n<span style=\"background-color: #ff9933; margin:5px;\">&nbsp;&nbsp;</span>\n Unhealthy for Sensitive Groups\n</div>\n\n<div >\n<span style=\"background-color: #cc0033; margin:5px;\">&nbsp;&nbsp;</span>\n Unhealthy\n</div>\n\n<div >\n<span style=\"background-color: #660099; margin:5px;\">&nbsp;&nbsp;</span>\n Very Unhealthy\n</div>\n\n<div >\n<span style=\"background-color: #7e0023;  margin:5px;\">&nbsp;&nbsp;</span>\n Hazardous\n</div>"
   }
  },
  {
   "title": "AQI (Air Quality Index) d3928b",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/d3928b/AQI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AQI (Air Quality Index) cf52c4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/cf52c4/AQI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter Values d3928b",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/d3928b/PM2-5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/d3928b/PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/d3928b/PM1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter Values cf52c4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/cf52c4/PM2-5",
     "query": "SELECT max(\"value\") FROM \"autogen\".\"sensor/cf52c4/PM2-5\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/cf52c4/PM10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor/cf52c4/PM1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}